version: 0.2

phases:
  pre_build:
    commands:
      - echo Retrieving environment variables from Parameter Store...
  build:
    commands:
      - echo Installing dependencies in root...
      - npm i --save
artifacts:
  files:
    - "Autoscan_Admin/build/**/*"
    - "Autoscan_Frontend/build/**/*"
