version: 0.2

phases:
  pre_build:
    commands:
      - echo Retrieving environment variables from Parameter Store...
  build:
    commands:
      - echo Installing and building Autoscan_Admin...
      - cd Autoscan_Admin
      - npm install -f
      - npm run build 
      - cd ..
      - echo Installing and building Autoscan_Frontend...
      - cd Autoscan_Frontend
      - npm install -f
      - npm run build
      - cd ..
      - echo Installing dependencies in root...
      - npm i --save
artifacts:
  files:
    - '**/*'